#!/usr/bin/env python3
"""Generate library.js from methodology-flowcharts.md.

Every ```mermaid fence in that document becomes a built-in diagram in the
editor, titled by the "## " heading above it. Edit the markdown, re-run this
script, then re-run build_single_file.py.
"""

import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent
SRC = HERE / "methodology-flowcharts.md"
OUT = HERE / "library.js"

# "## 4. Sentinel-2 preprocessing" -> "4. Sentinel-2 preprocessing"
HEADING = re.compile(r"^##\s+(.+?)\s*$", re.M)
FENCE = re.compile(r"^```mermaid\s*\n(.*?)^```\s*$", re.M | re.S)


def main() -> None:
    if not SRC.exists():
        sys.exit(f"ERROR: {SRC.name} not found")
    text = SRC.read_text(encoding="utf-8")

    headings = [(m.start(), m.group(1)) for m in HEADING.finditer(text)]
    diagrams = []

    for fence in FENCE.finditer(text):
        # The nearest "## " heading above this fence names the diagram.
        title = next((h for pos, h in reversed(headings) if pos < fence.start()), None)
        if title is None:
            sys.exit(f"ERROR: mermaid block at offset {fence.start()} has no heading above it")
        code = fence.group(1).rstrip() + "\n"
        diagrams.append({"name": title, "code": code})

    if not diagrams:
        sys.exit("ERROR: no ```mermaid blocks found")

    names = [d["name"] for d in diagrams]
    if len(set(names)) != len(names):
        sys.exit("ERROR: duplicate diagram headings; each needs a distinct title")

    banner = (
        "/* Generated by build_library.py from methodology-flowcharts.md.\n"
        " * Edit the markdown and re-run that script; do not edit this file. */\n"
    )
    body = json.dumps(diagrams, indent=2, ensure_ascii=False)
    OUT.write_text(f"{banner}window.MERMAID_EDITOR_LIBRARY = {body};\n", encoding="utf-8")

    print(f"Wrote {OUT.name} with {len(diagrams)} diagrams:")
    for d in diagrams:
        print(f"  - {d['name']}")


if __name__ == "__main__":
    main()
