#!/usr/bin/env python3
"""Fuse index.html + styles.css + app.js + vendor/mermaid.min.js into one
standalone HTML file (mermaid-editor.html) that runs with no other files
present. Run this after editing any of the sources:

    python3 build_single_file.py
"""

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent
OUT = HERE / "mermaid-editor.html"

BANNER = """<!--
  Mermaid Flowchart Editor — standalone single-file build.
  Generated by build_single_file.py; edit index.html / styles.css / app.js
  and re-run that script rather than editing this file directly.

  HOW TO OPEN: right-click this file, choose "Open with", and pick a browser
  (Chrome, Edge, Firefox, Safari). Double-clicking opens a text editor on
  machines where an editor owns the .html file type.

  Bundles Mermaid (https://github.com/mermaid-js/mermaid), MIT licensed.
-->
"""


def guard(js: str, label: str) -> str:
    """Make JS safe to inline inside a <script> element.

    The HTML tokenizer treats "</script" and "<!--" specially inside script
    data. Escaping the "<" keeps the JavaScript identical (\\< is just < in
    both string and regex context) while denying the parser those sequences.
    """
    js = js.replace("</script", "<\\/script")
    js = js.replace("<!--", "<\\!--")
    if re.search(r"</script|(?<!\\)<!--", js):
        sys.exit(f"ERROR: {label} still contains a sequence that breaks inlining")
    return js


def main() -> None:
    library_js = HERE / "library.js"
    if not library_js.exists():
        sys.exit("ERROR: library.js is missing — run build_library.py first")

    html = (HERE / "index.html").read_text(encoding="utf-8")
    css = (HERE / "styles.css").read_text(encoding="utf-8")
    app = (HERE / "app.js").read_text(encoding="utf-8")
    library = library_js.read_text(encoding="utf-8")
    lib = (HERE / "vendor" / "mermaid.min.js").read_text(encoding="utf-8")

    replacements = [
        ('<link rel="stylesheet" href="styles.css">', f"<style>\n{css}\n</style>"),
        ('<script src="vendor/mermaid.min.js"></script>',
         f"<script>\n{guard(lib, 'mermaid.min.js')}\n</script>"),
        ('<script src="library.js"></script>',
         f"<script>\n{guard(library, 'library.js')}\n</script>"),
        ('<script src="app.js"></script>',
         f"<script>\n{guard(app, 'app.js')}\n</script>"),
    ]

    for needle, block in replacements:
        if needle not in html:
            sys.exit(f"ERROR: could not find {needle!r} in index.html")
        html = html.replace(needle, block)

    html = html.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + BANNER, 1)
    OUT.write_text(html, encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size / 1_048_576:.1f} MB)")


if __name__ == "__main__":
    main()
